// --- Configuración del Teclado ---
export const keyLayout = [
    [{key:"º",size:1,group:6,finger:"pinky-left"}, {key:"1",size:1,group:6,finger:"pinky-left"}, {key:"2",size:1,group:4,finger:"ring-left"}, {key:"3",size:1,group:3,finger:"middle-left"}, {key:"4",size:1,group:1,finger:"index-left"}, {key:"5",size:1,group:1,finger:"index-left"}, {key:"6",size:1,group:2,finger:"index-right"}, {key:"7",size:1,group:2,finger:"index-right"}, {key:"8",size:1,group:3,finger:"middle-right"}, {key:"9",size:1,group:4,finger:"ring-right"}, {key:"0",size:1,group:6,finger:"pinky-right"}, {key:"'",size:1,group:6,finger:"pinky-right"}, {key:"¡",size:1,group:6,finger:"pinky-right"}, {key:"Backspace",label:"←",size:2,group:6,finger:"pinky-right"}],
    [{key:"Tab",size:1.5,group:6,finger:"pinky-left"}, {key:"Q",size:1,group:6,finger:"pinky-left"}, {key:"W",size:1,group:4,finger:"ring-left"}, {key:"E",size:1,group:3,finger:"middle-left"}, {key:"R",size:1,group:1,finger:"index-left"}, {key:"T",size:1,group:1,finger:"index-left"}, {key:"Y",size:1,group:2,finger:"index-right"}, {key:"U",size:1,group:2,finger:"index-right"}, {key:"I",size:1,group:3,finger:"middle-right"}, {key:"O",size:1,group:4,finger:"ring-right"}, {key:"P",size:1,group:6,finger:"pinky-right"}, {key:"`",size:1,group:6,finger:"pinky-right"}, {key:"+",size:1,group:6,finger:"pinky-right"}, {key:"\\",size:1.5,label:"",disabled:true,group:6}],
    [{key:"CapsLock",label:"Bloq Mayús",size:1.75,group:6,finger:"pinky-left"}, {key:"A",size:1,group:6,finger:"pinky-left"}, {key:"S",size:1,group:4,finger:"ring-left"}, {key:"D",size:1,group:3,finger:"middle-left"}, {key:"F",size:1,group:1,finger:"index-left"}, {key:"G",size:1,group:1,finger:"index-left"}, {key:"H",size:1,group:2,finger:"index-right"}, {key:"J",size:1,group:2,finger:"index-right"}, {key:"K",size:1,group:3,finger:"middle-right"}, {key:"L",size:1,group:4,finger:"ring-right"}, {key:"Ñ",size:1,group:6,finger:"pinky-right"}, {key:"´",size:1,group:6,finger:"pinky-right"}, {key:"Ç",size:1,group:6,finger:"pinky-right"}, {key:"Enter",size:1.25,group:6,finger:"pinky-right"}],
    [{key:"ShiftLeft",label:"Shift",size:1.25,group:6,finger:"pinky-left"}, {key:"<",size:1,group:6,finger:"pinky-left"}, {key:"Z",size:1,group:6,finger:"ring-left"}, {key:"X",size:1,group:4,finger:"middle-left"}, {key:"C",size:1,group:3,finger:"index-left"}, {key:"V",size:1,group:1,finger:"index-left"}, {key:"B",size:1,group:1,finger:"index-right"}, {key:"N",size:1,group:2,finger:"index-right"}, {key:"M",size:1,group:2,finger:"middle-right"}, {key:",",size:1,group:3,finger:"ring-right"}, {key:".",size:1,group:4,finger:"pinky-right"}, {key:"-",size:1,group:6,finger:"pinky-right"}, {key:"ShiftRight",label:"Shift",size:2.75,group:6,finger:"pinky-right"}],
    [{key:"CtrlLeft",label:"Ctrl",size:1.25,group:6,finger:"pinky-left"}, {key:"Win",size:1.25,group:6}, {key:"AltLeft",label:"Alt",size:1.25,group:5,finger:"thumb-left"}, {key:"Space",label:"",size:6.25,group:5,finger:"thumb"}, {key:"AltRight",label:"AltGr",size:1.25,group:5,finger:"thumb-right"}, {key:"Menu",size:1.25,group:6}, {key:"CtrlRight",label:"Ctrl",size:1.25,group:6,finger:"pinky-right"}]
];
export const diacriticMap = {
    'á': { base: 'a', deadKey: '´' }, 'é': { base: 'e', deadKey: '´' }, 'í': { base: 'i', deadKey: '´' }, 'ó': { base: 'o', deadKey: '´' }, 'ú': { base: 'u', deadKey: '´' }, 'ü': { base: 'u', deadKey: '¨' }
};